CREATE TABLE PRODUCTS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    sku VARCHAR(50) NOT NULL UNIQUE,

    name VARCHAR(200) NOT NULL,

    description TEXT,

    price NUMERIC(10, 2) NOT NULL,
    CONSTRAINT chk_product_price_non_negative CHECK (price > 0),

    category VARCHAR(100) NOT NULL,

    active BOOL NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id BIGINT NOT NULL,

    image_url VARCHAR(500) NOT NULL,

    display_order INTEGER NOT NULL,

    is_primary BOOL NOT NULL DEFAULT FALSE,

    CONSTRAINT fk_product_images_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE,

    CONSTRAINT chk_product_image_display_order_positive
        CHECK (display_order >= 1)
);

CREATE UNIQUE INDEX uq_product_images_one_primary
ON product_images (product_id)
WHERE is_primary = TRUE;